### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by qqbbdev** [stas-art/device#1]
When are you going to deploy first files?

**Comment by stas-art** [comment]
> When are you going to deploy first files?

I've got some problem with that.. when i tried to deploy, it send me error - 
![Screen Shot 2019-08-07 at 7 22 47 PM](https://user-images.githubusercontent.com/53872066/62639655-a3e52c80-b948-11e9-9b19-f65f11f7b8c0.png)

**Comment by stas-art** [comment]
> When are you going to deploy first files?

Ah okay sry, My bad..
